services: docker
env:
- distro: ubuntu1604
- distro: ubuntu1404
script:
- export container_id=$(date +%s)
- export cleanup=false
- wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
- chmod +x ${PWD}/tests/test.sh
- "${PWD}/tests/test.sh"
- 'sudo docker exec ${container_id} sh -c "[ -f /home/test_usr1/.zshrc ] && [ -f /home/test_usr2/.zshrc
  ]"

'
- 'sudo docker exec ${container_id} sh -c "cat /home/test_usr1/.zshrc | grep ^plugins=
  | grep test_plugin1 && cat /home/test_usr1/.zshrc | grep ^plugins= | grep test_plugin2"

'
- 'sudo docker exec ${container_id} sh -c "cat /home/test_usr2/.zshrc | grep ^plugins=
  | grep test_plugin3 && cat /home/test_usr2/.zshrc | grep ^plugins= | grep test_plugin4"

'
- 'sudo docker exec ${container_id} sh -c "cat /home/test_usr2/.zshrc | grep ^ZSH_THEME=.*test_theme2"

'
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      secure: 13w6eh6+OzusN58FIGAT7DLIvbM2jJoTfo5Mw9gx6sMALe9SAPTAtUb9QbGDQFc6I0PMroD+xE53xXF7N3Jlx5tk40KhKeGgvkPhaBoqIgfMYAeVUC3apcYczWvv5RIabl0R9I9irSc+bUeuImRaeYUMyYh1jPUhBYdzzd3Oorwwt0X6bqdDUA+xYEBEOoVQyTWsWa0NZJNdBhWMXauI65rAByKVvbo1ravfy4E48n7bPXJ161cp0bbTmL10tVQ5SA6+5p7okSARekZUTeO67Y/WsBw7OiJe6Aj2royB8gH7CJZuhReHIsFSKm2d8dsDS5UUoO0YL+urLg4qLyJ3JPukXymwkOqnkkeDvNqKysrE97u5e/1w8g4z6sZEJM7K7+1f0SzS5PXVZvU0lMJ/eVNXrNrKFxkjQO5zcXaqoqCde8RDMrDvXw+MQOjh/270l+kGqI6sYEpszmxaaJUuC855KSj6RHc/OH/L9VpMkSCuboRWRs1S5BRITAY7wLs8G2nhdGs3I8ICgEv3mN1BhDfhbj7oA9/Nq445ZibKhkR3CwM5DFqWROJYjLR9Tgz73Wy9s/fTuXicK40Kgk2F/UCYMJds8TzuSkH7dC34YFYPHs4wySg8iKB7GNMC5glLHfpc8FYJ8Q4k6lBCn4fe3raDqJIIBkBr9oUatFy/Hpw=
